---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      python:
        patterns:
          - "*"
        exclude-patterns:
          - ruff
          - libtimed
