---
stages:
  - "build"

image: "python:3.11"

build:
  stage: "build"
  before_script:
    - pip install poetry
    # change source to SSH
    - sed -i "s/git@git.adfinis.com:/https:\/\/gitlab-ci-token:$CI_JOB_TOKEN@git.adfinis.com\//" pyproject.toml

  script:
    - poetry install
    - poetry build
    - poetry config repositories.gitlab "https://git.adfinis.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish --repository gitlab
