---
name: Alex Says

on: [pull_request_target]

jobs:
  alexjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: Comment on new PR
        uses: brown-ccv/alex-recommends@v1.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message_id: 'alex'
          pr_only: false
