---

name: Semantic Release
on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@v1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump Poetry
        if: github.ref == 'refs/heads/main' && steps.semrel.outputs.version != ''
        run: poetry version ${{ steps.release.outputs.version }}

      - uses: EndBug/add-and-commit@v9
        if: github.ref == 'refs/heads/main' && steps.release.outputs.version != ''
        with:
          message: "chore(version): bump"
          default_author: github_actions
          add: pyproject.toml
